name: Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test-deploy:
    name: Test Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Enable Corepack for Modern Yarn
        run: corepack enable
      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable
      - name: Check Markdown formatting
        run: ./scripts/linter.sh
      - name: Test build website
        run: yarn build

  test-links:
    name: Test Links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Enable Corepack for Modern Yarn
        run: corepack enable
      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable
      - name: Check internal links
        run: yarn run remark --use remark-validate-links --no-config --frail ./docs
      - name: Check external links
        run: yarn run remark --use remark-lint-no-dead-urls --frail ./docs
      